spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marking?serverTimezone=GMT%2B8 & characterEnconding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf:
#    cache: false
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com/xiaoman/dao


